# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'MZEDU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MZEDU
  pod 'SnapKit'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'NidThirdPartyLogin'
end
